#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : earlyoom
Version  : 1.3
Release  : 1
URL      : https://github.com/rfjakob/earlyoom/archive/v1.3.tar.gz
Source0  : https://github.com/rfjakob/earlyoom/archive/v1.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: earlyoom-license = %{version}-%{release}
BuildRequires : buildreq-golang
BuildRequires : systemd

%description
The Early OOM Daemon
====================
[![Build Status](https://api.travis-ci.org/rfjakob/earlyoom.svg)](https://travis-ci.org/rfjakob/earlyoom)
[![MIT License](https://img.shields.io/badge/license-MIT-blue.svg)](LICENSE)

%package license
Summary: license components for the earlyoom package.
Group: Default

%description license
license components for the earlyoom package.


%prep
%setup -q -n earlyoom-1.3
cd %{_builddir}/earlyoom-1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1578436091
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1578436091
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/earlyoom
cp %{_builddir}/earlyoom-1.3/LICENSE %{buildroot}/usr/share/package-licenses/earlyoom/49c65c4ad5a142b45b01486ac9df8f15d9d6d30b
%make_install

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/earlyoom/49c65c4ad5a142b45b01486ac9df8f15d9d6d30b
